# -*- coding: utf-8 -*-
"""fraud_detection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDRCNFZtbCokIG0d_-amBvufDSGfkvr1
"""

# import the necessary libraries

import streamlit as st

import pandas as pd

import joblib

model = joblib.load("/content/drive/MyDrive/fraud_detection_pipleine.pkl")

st.title("Fraud Detection Prediction App")

st.markdown("Please enter the transaction details to predict fraud and press the predict button")

st.divider()

transaction_id = st.selectbox("Transaction Type", ["PAYMENT", "TRANSFER", "CASH_OUT", "DEPOSIT"])

amount = st.number_input("Amount", min_value = 0.0, value=1000.0)

oldbalanceOrg = st.number_input("Old Balance (Sender)", min_value=0.0, value=10000.0)

newbalanceOrig = st.number_input("New Balance (Sender)", min_value=0.0, value=9000.0)

oldbalanceDest = st.number_input("Old Balance (Receiver)", min_value=0.0, value=0.0)

newbalanceDest = st.number_input("New Balance (Receiver)", min_value=0.0, value=0.0)

#define the prediction button

if st.button("Predict"):
  input_data = pd.DataFrame([{
      "type": transaction_type,
      "amount": amount,
      "oldbalanceOrg": oldbalanceOrg,
      "newbalanceOrig": newbalanceOrig,
      "oldbalanceDest": oldbalanceDest,
      "newbalanceDest": newbalanceDest
  }])
  prediction = model.predict(input_data)[0]
  st.subheader(f"Prediction: '{int(prediction)}'")

  if prediction ==1:
    st.error("This transaction can be fraud")
  else:
    st.success("This transaction is not fraud")